name: transformerextsum
channels:
    - conda-forge
    - pytorch
dependencies:
    - pytorch
    - scikit-learn
    - tensorboard
    - spacy
    - pip
    - pip:
      - pytorch_lightning
      - transformers
      - qhoptim
      - wandb
      - rouge-score